export const jobs = [
  {
    title: '2D Animation Director',
    slug: '2d-animation-director',
    worktime: 'Full-time',
    team: 'Animation',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Lead and support the animation team to ensure that everyone has the necessary skills and resources to complete their tasks.',
      'Collaborate closely with the director, scriptwriter, and production team to establish the project\'s visual style and production plan.',
      'Create stunning visual storyboards, color scripts',
      'Create and refine animation scenes and movements that align with the project\'s vision.',
      'Oversee and manage the entire animation production process, from initiation to completion.',
      'Ensure high-quality animation by monitoring and meeting all project quality requirements within the designated timeline.'
    ],
    requirements: [
      'At least 5-7 years of experience in the animation industry.',
      'Proficiency in animation software such as ClipStudio Paint Ex, Toon Boon',
      'Strong leadership skills, with the ability to mentor and develop the animation team.',
      'Competency in reading and comprehending scripts, graphics, and other documents pertaining to animation production.',
      'Excellent communication skills, both verbal and written, and the ability to effectively convey ideas and concepts to team members.',
      'Highly responsible and skilled in time management.',
      'Willingness to learn, adapt, and embrace new ideas and techniques in the field.',
    ],
    weOffer: [
      'Competitive compensation.',
      'Beautiful working space located in the heart of the city, that includes free facilities, such as gym, swimming pool, library, and more',
      'An environment that fosters creativity and personal growth. Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays, in accordance with legal requirements.',
    ]
  },
  {
    title: '2D Concept Artist',
    slug: '2d-concept-artist',
    worktime: 'Full-time',
    team: 'Сoncept',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Collaborate with the content team to understand the order\'s content, contribute ideas to develop and showcase the company\'s artwork products (Character, Flash art, Poster, Storyboard, etc.).',
      'Create and quickly sketch overall concept artwork, or detailed artwork based on agreed-upon requirements and ideas.',
      'Coordinate with other processes to ensure consistency and quality of the final product according to the set ideas and requirements.',
      'Enthusiastically and flexibly support the artist team to the best of one\'s ability when necessary.',
      'Propose and actively contribute opinions to develop and improve one\'s own skills, as well as the collective.',
    ],
    requirements: [
      'Bachelor\'s degree or equivalent in graphic design, industrial art.',
      'Minimum 5 years of professional experience as a concept artist.',
      'Solid knowledge of anatomy, spatial composition, and understanding of animation.',
      'Ability to create blockouts, generate ideas, and design backgrounds, props, buildings, creatures, etc.',
      'Adaptability to various art styles (Anime, Manga, Comic, etc.)',
      'Proficiency in using Wacom drawing tablets and graphic design software such as Photoshop, Sketchbook Pro, Paint Tool Sai, Clip Studio Paint, or similar.',
      'Proactive attitude, self-learning, and open-mindedness.',
      'Ability to work well and collaborate in a team environment.',
      'Open to receiving feedback from superiors and colleagues.',
      'Interest in self-study through artbooks, anime, movies to apply, find references, analyze orders.',
    ],
    weOffer: [
      'Competitive salary',
      'Beautiful working space located in the heart of the city, that includes free facilities, such as gym, swimming pool, library, and more',
      'An environment that fosters creativity and personal growth. Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays, in accordance with legal requirements.',
      'Comprehensive benefits and insurance package.',
    ]
  },
  {
    title: '2D General Anime Artist',
    slug: '2d-general-anime-artist',
    worktime: 'Full-time',
    team: 'Сoncept',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Assist with line-based color rendering or design props for the company based on orders and existing concepts.',
      'Coordinate with other departments to ensure consistency and quality in the final product, according to the required ideas.',
      'Provide enthusiastic and flexible support to the artist team to the best of my abilities when necessary.',
      'Make proposals and actively contribute ideas to develop and improve my own skills as well as the team\'s.',
    ],
    requirements: [
      'Minimum 2 years of experience in the 2D artist position.',
      'Have a rich imagination and diverse creativity, adaptable to various art styles.',
      'Use Wacom drawing tablets and graphic design software such as Photoshop, Sketchbook Pro, Paint Tool Sai, Clip Studio Paint, or similar.',
      'Have a progressive mindset, self-learning, and not being conservative.',
      'Good ability to work and collaborate in a team environment.',
      'Open to receiving feedback from superiors and colleagues.',
      'Have a preference for self-learning through artbooks, anime, movies to apply, find references, and analyze orders.',
    ],
    weOffer: [
      'Competitive compensation.',
      'Beautiful working space located in the heart of the city, that includes free facilities, such as gym, swimming pool, library, and more',
      'An environment that fosters creativity and personal growth. Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays, in accordance with legal requirements.',
      'Comprehensive benefits and insurance package.',
    ]
  },
  {
    title: 'Content Creators',
    slug: 'content-creators',
    worktime: 'Full-time',
    team: 'Сoncept',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Develop creative plans and implement content for animated characters on social media platforms (Tiktok, Instagram).',
      'Research competitors, analyze viewer insights to plan and deploy the best communication and content strategies.',
      'Contribute to setting goals, planning, and executing marketing campaigns for media and content management.',
    ],
    requirements: [
      'Minimum of 1-2 years of experience in a similar position. Candidates with experience in media and content in the animation, gaming, and anime industries are preferred.',
      'High creativity, sharp thinking, logical mindset, and proactive in work.',
      'Able to read English texts.',
      'Willingness to learn, grow, and adapt. Ability to work independently, seek and embrace new challenges in work.',
      'Deep involvement in animation, comics, and major art projects.',
    ],
    weOffer: [
      'Competitive compensation.',
      'Beautiful working space located in the heart of the city, that includes free facilities, such as gym, swimming pool, library, and more',
      'An environment that fosters creativity and personal growth. Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays, in accordance with legal requirements.',
      'Comprehensive benefits and insurance package.',
    ]
  },
];