export const jobs = [
  {
    title: '2D Animation Director',
    slug: '2d-animation-director',
    worktime: 'Full-time',
    team: 'Animation',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Lead and support the animation team to ensure that everyone has the necessary skills and resources to complete their tasks.',
      'Collaborate closely with the director, scriptwriter, and production team to establish production plans.',
      'Create stunning visual storyboards and color scripts.',
      'Create and refine animation scenes and movements that align with a project\'s vision.',
      'Oversee and manage the entire animation production process, from initiation to completion.',
      'Ensure high-quality animation by monitoring and meeting all project quality requirements within the designated timeline.',
    ],
    requirements: [
      'At least 5-7 years of experience in the animation industry.',
      'Proficiency in animation software such as ClipStudio Paint Ex and Toon Boom.',
      'Strong leadership skills, with the ability to mentor, develop, and grow the animation team.',
      'Competency in reading and comprehending scripts, graphics, and other documents pertaining to animation production.',
      'Excellent communication skills, both verbal and written, and the ability to effectively convey ideas and concepts to team members.',
      'Highly responsible and skilled in time management.',
      'Willingness to learn, adapt, and embrace new ideas and techniques in the field.',
    ],
    weOffer: [
      'Competitive compensation.',
      'Beautiful working space located in the heart of the city, with free facilities such as a gym, swimming pool, library, and more. (For applicants in Ho Chi Minh).',
      'An environment that fosters creativity and personal growth.',
      'Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays in accordance with legal requirements.'
    ]
  },
  {
    title: '2D Concept Artist',
    slug: '2d-concept-artist',
    worktime: 'Full-time',
    team: 'Сoncept',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Collaborate with the content team to understand the objective, and contribute ideas to develop and showcase the company\'s products (Character designs, Flash art, Poster, Storyboard, etc.).',
      'Create and sketch overall concept artworks or detailed artworks.',
      'Coordinate with other team members to ensure consistency and quality of the final product according to the set ideas and requirements.',
      'Propose and actively contribute opinions to develop and improve your own skills.',
    ],
    requirements: [
      'Bachelor\'s degree or equivalent in graphic design or industrial art.',
      'Minimum of 5 years of professional experience as a concept artist.',
      'Solid knowledge of anatomy, spatial composition, and understanding of animation.',
      'Ability to create blockouts, generate ideas, and design backgrounds, props, buildings, creatures, etc.',
      'Adaptability to various art styles (Anime, Manga, Comics, etc.).',
      'Proficiency in using Wacom drawing tablets and graphic design software such as Photoshop, Sketchbook Pro, Paint Tool Sai, Clip Studio Paint, or similar.',
      'Ability to work well and collaborate in a team environment.',
      'Openness to receiving feedback from colleagues.',
    ],
    weOffer: [
      'Competitive salary.',
      'Beautiful working space located in the heart of the city, with free facilities such as a gym, swimming pool, library, and more. (For applicants in Ho Chi Minh).',
      'An environment that fosters creativity and personal growth.',
      'Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays in accordance with legal requirements.',
      'Comprehensive benefits and insurance package.',
    ]
  },
  {
    title: '2D General Anime Artist',
    slug: '2d-general-anime-artist',
    worktime: 'Full-time',
    team: 'Сoncept',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Assist with line-based color rendering or design props based on project requirements.',
      'Coordinate with other departments to ensure consistency and quality in the final product.',
      'Provide enthusiastic and flexible support to the artist team to the best of your abilities when necessary.',
      'Make proposals and actively contribute ideas to develop and improve your own skills as well as the team\'s.',
    ],
    requirements: [
      'Minimum 2 years of experience as a 2D artist.',
      'Adaptability to various art styles.',
      'Proficiency in using Wacom drawing tablets and graphic design software such as Photoshop, Sketchbook Pro, Paint Tool Sai, Clip Studio Paint, or similar.',
      'Ability to work and collaborate in a team environment.',
      'Openness to receiving feedback from colleagues.',
      'Preference for self-learning through artbooks, anime, and movies to apply, find references, and analyze client’s requests.',
    ],
    weOffer: [
      'Competitive compensation.',
      'Beautiful working space located in the heart of the city, with free facilities such as a gym, swimming pool, library, and more. (For applicants in Ho Chi Minh).',
      'An environment that fosters creativity and personal growth.',
      'Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays in accordance with legal requirements.',
    ]
  },
  {
    title: 'Content Creators',
    slug: 'content-creators',
    worktime: 'Full-time',
    team: 'Сoncept',
    location: 'Ho Chi Minh City',
    generallocation: 'Ho Chi Minh City or Remote',
    text: 'Animation  //  Ho Chi Minh City or Remote',
    responsibilities: [
      'Develop content plans and implement ideas for animation videos on social media platforms (TikTok, Instagram).',
      'Research competitors and analyze viewer insights to plan and deploy the best communication and content strategies.',
      'Contribute to setting goals, planning, and executing marketing campaigns for media and content management.',
    ],
    requirements: [
      'Minimum of 2 years of experience in a similar position. Candidates with experience in media and content in the animation, gaming, and anime industries are preferred.',
      'High creativity, sharp thinking, logical mindset, and proactivity in work.',
      'Ability to communicate in English',
      'Willingness to learn, grow, and adapt. Ability to work independently, seek, and embrace new challenges.',
      'Deep involvement in anime, western animation, comics, and major art projects.',
    ],
    weOffer: [
      'Competitive compensation.',
      'Beautiful working space located in the heart of the city, with free facilities such as a gym, swimming pool, library, and more. (For applicants in Ho Chi Minh).',
      'An environment that fosters creativity and personal growth.',
      'Biannual salary reviews.',
      'Company-provided work equipment.',
      'Paid holidays in accordance with legal requirements.',
    ]
  },
];